CREATE DATABASE IF NOT EXISTS bpjstk;
USE bpjstk;
DROP TABLE IF EXISTS transactions;
CREATE SEQUENCE ID START 1;
CREATE TABLE transactions (
    ID serial PRIMARY KEY,
    FULLNAME VARCHAR(256) NOT NULL,
    QUANTITY FLOAT NOT NULL,
    PRICE VARCHAR(256) NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT Now(),
    UPDATED_AT TIMESTAMPTZ DEFAULT Now() 
);